# Generated by Django 3.1.7 on 2021-03-20 19:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('party_name', models.CharField(default='', max_length=50)),
                ('district', models.CharField(default='', max_length=50)),
                ('register_date', models.DateField(verbose_name=datetime.datetime(2021, 3, 21, 1, 16, 10, 820389))),
            ],
        ),
    ]
