# Generated by Django 3.1.7 on 2021-03-21 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0004_auto_20210321_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='aadhar_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidate',
            name='gender',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='candidate',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 3, 21, 16, 5, 50, 124434)),
        ),
    ]
