# Generated by Django 3.1.7 on 2021-03-26 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0009_auto_20210321_1628'),
        ('Evoting_app', '0007_auto_20210321_1629'),
    ]

    operations = [
    ]
