# Generated by Django 3.1.7 on 2021-04-04 07:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0013_merge_20210404_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 12, 36, 58, 372145)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 4, 12, 36, 58, 373142)),
        ),
    ]
