# Generated by Django 3.1.7 on 2021-04-04 19:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0014_auto_20210404_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 0, 32, 30, 382906)),
        ),
        migrations.AlterField(
            model_name='voter',
            name='register_date',
            field=models.DateField(default=datetime.datetime(2021, 4, 5, 0, 32, 30, 382906)),
        ),
    ]
