# Generated by Django 3.1.7 on 2021-04-05 19:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0015_auto_20210405_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='voter',
            name='register_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
