# Generated by Django 3.1.7 on 2021-04-06 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0017_auto_20210406_1434'),
        ('Evoting_app', '0016_auto_20210406_0034'),
    ]

    operations = [
    ]
