# Generated by Django 3.1.7 on 2021-04-06 15:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Evoting_app', '0019_voted'),
    ]

    operations = [
        migrations.AddField(
            model_name='voted',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='voted',
            name='name',
            field=models.IntegerField(),
        ),
    ]
